from django.conf.urls.defaults import *

urlpatterns = patterns('djforms.eventform.views',
  url(r'^data_entered/$',
      view    = 'data_entered',
      name    = 'data_entered',
  ),
  url(r'^event_create/$',
      view    = 'event_create',
      name    = 'event_create',
  ),
  url(r'^event_manage_list/(?P<page>\w)/$',
      view    = 'event_manage_list',
      name    = 'event_manage_list_paginated',
  ),
  url(r'^event_manage_list/$',
      view    = 'event_manage_list',
      name    = 'event_manage_list',
  ),
  url(r'^event_manage/(?P<slug>[-\w]+)/$',
      view    = 'event_manage',
      name    = 'event_manage',
  ),
  url(r'^registrant/(?P<slug>[-\w]+)/$',
      view    = 'registrant_detail',
      name    = 'registrant_detail',
  ),
  url(r'^registrants/page/(?P<page>\w)/$',
      view    = 'registrant_list',
      name    = 'registrant_list_paginated',
  ),
  url(r'^registrants/$',
      view    = 'registrant_list',
      name    = 'registrant_list',
  ),
  url(r'^search/$',
      view    = 'search',
      name    = 'event_search',
  ),
  url(r'^page/(?P<page>\w)/$',
      view    = 'event_list',
      name    = 'event_index_paginated',
  ),
  url(r'^$',
      view    = 'event_list',
      name    = 'event_index',
  ),
    url(r'^(?P<slug>[-\w]+)/$',
      view    = 'event_detail',
      name    = 'event_detail',
  ),
)
