from django.conf.urls.defaults import *

urlpatterns = patterns('',
  url(r'^data_entered/$',
      view    = 'jobpost.views.data_entered',
      name    = 'data_entered',
  ),
  url(r'^createpost/$',
      view    = 'jobpost.views.post_create',
      name    = 'post_create',
  ),
  url(r'^categories/(?P<slug>[-\w]+)/$',
      view    = 'jobpost.views.category_detail',
      name    = 'category_detail',
  ),
  url(r'^categories/page/(?P<page>\w)/$',
      view    = 'jobpost.views.category_list',
      name    = 'category_list_paginated',
  ),
  url(r'^categories/$',
      view    = 'jobpost.views.category_list',
      name    = 'category_list',
  ),
  url(r'^search/$',
      view    = 'jobpost.views.search',
      name    = 'post_search',
  ),
  url(r'^page/(?P<page>\w)/$',
      view    = 'jobpost.views.post_list',
      name    = 'post_index_paginated',
  ),
  url(r'^$',
      view    = 'jobpost.views.post_list',
      name    = 'post_index',
  ),
    url(r'^(?P<slug>[-\w]+)/$',
      view    = 'jobpost.views.post_detail',
      name    = 'post_detail',
  ),
)
